export const MoviesActionTypes = {
  API: 'API',
  SET_DISCOVER_MOVIES: 'SET_DISCOVER_MOVIES',
  SET_NOW_PLAYING_MOVIES: 'SET_NOW_PLAYING_MOVIES',
  SET_UPCOMING_MOVIES: 'SET_UPCOMING_MOVIES',
  SET_CAST_AND_CREW: 'SET_CAST_AND_CREW',
};
